# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('autenticacao', '0003_auto_20171105_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciamentoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_local', models.BooleanField(default=False, verbose_name='É Local?')),
                ('grupo_gerenciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_gerenciador_set', to='auth.Group')),
                ('grupos_gerenciados', models.ManyToManyField(related_name='grupos_gerenciados_set', to='auth.Group')),
            ],
            options={
                'verbose_name': 'Gerenciamento de Grupo',
                'verbose_name_plural': 'Gerenciamento de Grupos',
            },
        ),
    ]
