# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0022_auto_20180919_2147'),
        ('autenticacao', '0005_auto_20180525_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dizimo.Paroquia'),
        ),
    ]
