# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 19:11
from __future__ import unicode_literals

from django.db import migrations


def adiciona_paroquia_perfis(apps, schema_editor):
    # importa modelos
    Paroquia = apps.get_model('dizimo', 'Paroquia')
    Perfil = apps.get_model('autenticacao', 'Perfil')
    # pega referencia paraquia
    paroquia = Paroquia.objects.first()
    # adiciona paroquia nos registros
    Perfil.objects.all().update(paroquia=paroquia)


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_perfil_paroquia'),
    ]

    operations = [
        migrations.RunPython(adiciona_paroquia_perfis),
    ]
