# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizimista',
            name='data_nascimento',
            field=models.DateField(verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='endereco',
            field=models.CharField(max_length=250, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='dizimista',
            name='paroquia',
            field=models.CharField(max_length=100, verbose_name='paróquia'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=15, verbose_name='número'),
        ),
    ]
