# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0005_auto_20171105_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='valor_currency',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
