# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0006_auto_20171105_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='valor',
        ),
    ]
