# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0007_remove_oferta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
