# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0010_auto_20180211_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dizimista',
            name='paroquia',
        ),
    ]
