# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0014_igreja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='descrição'),
        ),
    ]
