# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 20:47
from __future__ import unicode_literals

from django.db import migrations
# from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0015_auto_20180330_1747'),
    ]

    operations = [
        # UnaccentExtension()
    ]
