# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0019_auto_20180629_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='batismo',
            name='hora_batismo',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='hora do batismo'),
            preserve_default=False,
        ),
    ]
