# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0021_auto_20180908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroquia',
            name='endereco',
            field=models.CharField(default='', max_length=250, verbose_name='endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
