# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0022_auto_20180919_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
