# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 18:26
from __future__ import unicode_literals

from django.db import migrations


def adiciona_paroquia_recebimentos_pagamentos(apps, schema_editor):
    # importa modelos
    Paroquia = apps.get_model('dizimo', 'Paroquia')
    Oferta = apps.get_model('dizimo', 'Oferta')
    Dizimo = apps.get_model('dizimo', 'Dizimo')
    Batismo = apps.get_model('dizimo', 'Batismo')
    Doacao = apps.get_model('dizimo', 'Doacao')
    Pagamento = apps.get_model('dizimo', 'Pagamento')
    # pega referencia paraquia
    paroquia = Paroquia.objects.first()
    # adiciona paroquia nos registros
    Oferta.objects.all().update(paroquia=paroquia)
    Dizimo.objects.all().update(paroquia=paroquia)
    Batismo.objects.all().update(paroquia=paroquia)
    Doacao.objects.all().update(paroquia=paroquia)
    Pagamento.objects.all().update(paroquia=paroquia)


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0025_auto_20180923_1525'),
    ]

    operations = [
        migrations.RunPython(adiciona_paroquia_recebimentos_pagamentos),
    ]
