# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0032_oferta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data'),
            preserve_default=False,
        ),
    ]
