# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0033_doacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data'),
            preserve_default=False,
        ),
    ]
