# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 12:22
from __future__ import unicode_literals

from django.db import migrations


def adiciona_data_dizimo(apps, schema_editor):
    # importa modelos
    Dizimo = apps.get_model('dizimo', 'Dizimo')
    # percorre pagamentos
    for dizimo in Dizimo.objects.all():
        # seta data com base em cadastrado_em
        dizimo.data = dizimo.cadastrado_em
        dizimo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0036_auto_20181221_0922'),
    ]

    operations = [
        migrations.RunPython(adiciona_data_dizimo),
    ]
