# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0037_atribui_data_dizimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizimo',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
    ]
