version: "3"
services:
  web:
    container_name: web
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "80:80"
    networks:
      - backend
  db_sdizimo:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    volumes:
      - /Sdizimo/DB:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge