# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Operador')], default=2),
        ),
    ]
