# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_auto_20171103_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='usuarios/fotos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Operador')], default=1),
        ),
    ]
