# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_gerenciamentogrupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('view_perfil', 'Can view perfil'), ('list_perfil', 'Can list perfil'))},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Operador'), (3, 'Supervisor')], default=1),
        ),
    ]
