# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_atribui_paroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia'),
        ),
    ]
