# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('paroquia', models.CharField(max_length=100)),
                ('comunidade', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[['M', 'Masculino'], ['F', 'Feminino']], max_length=1)),
                ('estado_civil', models.CharField(choices=[['C', 'Casado'], ['S', 'Solteiro'], ['D', 'Divorciado']], max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=9)),
                ('tipo', models.CharField(choices=[['CEL', 'Celular'], ['COM', 'Comercial'], ['RES', 'Residencial']], max_length=3)),
                ('operadora', models.CharField(choices=[['CLARO', 'Claro'], ['NET', 'Net'], ['OI', 'Oi'], ['TIM', 'Tim'], ['TVN', 'TVN'], ['VIVO', 'Vivo']], max_length=5)),
                ('dizimista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='dizimo.Dizimista')),
            ],
        ),
    ]
