# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:28
from __future__ import unicode_literals

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0002_auto_20171014_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='estado',
            field=localflavor.br.models.BRStateField(default='MA', max_length=2),
            preserve_default=False,
        ),
    ]
