# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0003_dizimista_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dizimista',
            options={'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='dizimista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dizimistas/fotos'),
        ),
    ]
