# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dizimo', '0005_auto_20171122_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebida_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_batizando', models.CharField(max_length=250, verbose_name='nome do batizando')),
                ('nome_solicitante', models.CharField(max_length=250, verbose_name='nome do solicitante')),
                ('data_batizado', models.DateField(verbose_name='data do batizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'ordering': ('-data_batizado',),
            },
        ),
    ]
