# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0006_batismo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batismo',
            options={'ordering': ('-data_batismo',)},
        ),
        migrations.RemoveField(
            model_name='batismo',
            name='data_batizado',
        ),
        migrations.AddField(
            model_name='batismo',
            name='data_batismo',
            field=models.DateField(default=datetime.date(2017, 11, 24), verbose_name='data do batismo'),
            preserve_default=False,
        ),
    ]
