# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0013_auto_20180211_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250, verbose_name='endereço')),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
