# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0016_auto_20180330_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batismo',
            options={'ordering': ('-data_batismo',), 'permissions': (('view_batismo', 'Can view batismo'), ('list_batismo', 'Can list batismo'))},
        ),
        migrations.AlterModelOptions(
            name='dizimista',
            options={'ordering': ('nome',), 'permissions': (('view_dizimista', 'Can view dizimista'), ('list_dizimista', 'Can list dizimista'))},
        ),
        migrations.AlterModelOptions(
            name='dizimo',
            options={'ordering': ('-referencia', '-recebida_em'), 'permissions': (('view_dizimo', 'Can view dizimo'), ('list_dizimo', 'Can list dizimo'))},
        ),
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ('-recebida_em',), 'permissions': (('view_doacao', 'Can view doacao'), ('list_doacao', 'Can list doacao'))},
        ),
        migrations.AlterModelOptions(
            name='igreja',
            options={'permissions': (('view_igreja', 'Can view igreja'), ('list_igreja', 'Can list igreja'))},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ('-recebida_em',), 'permissions': (('view_oferta', 'Can view oferta'), ('list_oferta', 'Can list oferta'))},
        ),
        migrations.AlterModelOptions(
            name='paroquia',
            options={'ordering': ('nome',), 'permissions': (('view_paroquia', 'Can view paroquia'), ('list_paroquia', 'Can list paroquia'))},
        ),
    ]
