# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dizimo', '0017_auto_20180525_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
            options={
                'ordering': ('-cadastrado_em',),
                'permissions': (('view_pagamento', 'Can view pagamento'), ('list_pagamento', 'Can list pagamento')),
            },
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
            ],
            options={
                'ordering': ('descricao',),
                'permissions': (('view_tipopagamento', 'Can view tipopagamento'), ('list_tipopagamento', 'Can list tipopagamento')),
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='dizimo.TipoPagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
