# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0023_auto_20180919_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroquia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paroquia',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True),
        ),
    ]
