# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0024_auto_20180923_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='batismo',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AddField(
            model_name='dizimo',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='paroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
    ]
