# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0026_atribui_paroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batismo',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AlterField(
            model_name='dizimo',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizimo.Paroquia', verbose_name='paróquia'),
        ),
    ]
