# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0027_auto_20180923_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Igreja',
        ),
    ]
