# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 01:16
from __future__ import unicode_literals

from django.db import migrations


def adiciona_paroquia_tipo_pagamento(apps, schema_editor):
    # importa modelos
    Pagamento = apps.get_model('dizimo', 'Pagamento')
    # percorre pagamentos
    for pagamento in Pagamento.objects.all():
        # adiciona paroquia no tipo pagamento
        tipo = pagamento.tipo
        tipo.paroquia = pagamento.paroquia
        tipo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0029_tipopagamento_paroquia'),
    ]

    operations = [
        migrations.RunPython(adiciona_paroquia_tipo_pagamento),
    ]
