# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0035_auto_20181116_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dizimo',
            options={'ordering': ('-referencia', '-data'), 'permissions': (('view_dizimo', 'Can view dizimo'), ('list_dizimo', 'Can list dizimo'))},
        ),
        migrations.AddField(
            model_name='dizimo',
            name='data',
            field=models.DateField(null=True, verbose_name='data'),
        ),
    ]
